### ISSUE TITLE
Ajuda sobre código - Conv2D

### ISSUE THREAD

**Issue by Kallita** [luisfredgs/keras-cnn-handwriting-mnist#2]
Boa tarde,
Ao tentar reproduzir o código para aprendizagem, aparece um erro relacionado a seguinte linha:
model.add(Conv2D(30, (5, 5), input_shape=(1, 28, 28), activation='relu'))
Erro
AttributeError: module 'tensorflow._api.v2.config' has no attribute 'experimental_list_devices'

Fiz pesquisas e tentei escrever conforme abaixo (também não funcionou):
model.add(Conv2D(30, (5,5), activation='relu', padding='same',input_shape=(1,28,28), data_format='channels_first'))

A única alteração que fiz foi em uma linha de código que para nova versão do tensorflow não funcionava:
Antes:
from keras import backend as K 
#K.tensorflow_backend.set_image_dim_ordering('th')

Atualizei para:
from keras import backend as K 
K.common.set_image_dim_ordering('th')

Poderia me ajudar?? Muito obrigada!!

**Comment by luisfredgs** [comment]
Olá, jovem. Tudo bem?
Realmente, havia uma pequena incompatibilidade do código com as versões mais atuais do Tensorflow. Já providenciei o ajuste e você tentar novamente.

**Comment by Kallita** [comment]
Boa noite, muito obrigada pelo retorno!!!. O código funcionou . Muito grata .
